### PR TITLE
Fixing IServiceProvider.GetService implementation (fixes #376)

### LINKED ISSUE #376: KernelBase is implementing IServiceProvider.GetService incorrectly
According to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.iserviceprovider.getservice?view=netframework-4.5) of `IServiceProvider`, the method `GetService` is supposed to return `null` if there is no service object of the requested service type. `KernelBase` however delegates the call to the `Get` method which throws an exception in that case instead of delegating to the `TryGet` method which would be in line with the documentation.

This little quirk is the cause of some relatively weird and unnecessary workarounds when trying to integrate Ninject into a context like ASP.NET Core which mostly relies on the `IServiceProvider` interface. Effectively, one has to create a separate `IServiceProvider` implementation that wraps the kernel instead of just using the kernel directly.

As far as I can tell, that has been the expected behavior of the `IServiceProvider` from the very beginning and the Ninject implementation is just slightly off-spec.

### PR DESCRIPTION
**Pull request by lord-executor**
The problem is described in https://github.com/ninject/Ninject/issues/376 and the solution is straight forward. I have added two test cases for the `StandardKernel` to ensure that the `IServiceProvider` implementation is compliant with the behavior defined in the documentation.

### CODE REVIEW

**Comment by dadhi** [comment]
@lord-executor Hi and sorry for introdung.
The change seems to be a breaking change.
Maybe it is better to intruduce the config option to enable the proper behavior, and then in the next major version make the breaking change?

**Comment by lord-executor** [comment]
@dadhi intrude away my friend ;) - I call it collaboration

It's true, it does seem a bit breaking and I'll gladly add a configuration option to toggle old / new behavior. But the simple fact is: the current implementation is _incorrect_, so I would propose to make the **correct** behavior the default and reverting back an optional configuration.

**Comment by dadhi** [comment]
> I would propose to make the correct behavior the default and reverting back an optional configuration

That's a nice solution.

**Comment by scott-xu** [comment]
Thanks! @lord-executor @dadhi

**Pull request merged**
