### PR TITLE
Improve performance and reduce allocations in Selector

### PR DESCRIPTION
**Pull request by drieseng**
* Improves performance and reduce allocations in **Selector**.
* Adds unit tests for **Selector**.
* Adds benchmarks for **Selector**.

Note:
One part of the improvement comes from changing the return value of `ISelector.SelectConstructorsForInjection(Type type)` (and implementing classes) from **IEnumerable<ConstructorInfo>** to **ConstructorInfo[]**.

**Before:**

|                                                                                     Method |       Mean |      Error |     StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|------------------------------------------------------------------------------------------- |-----------:|-----------:|-----------:|------------:|------------:|------------:|--------------------:|
|                                                                                Constructor |   726.7 ns | 14.5146 ns | 19.8678 ns |      0.0458 |      0.0172 |      0.0038 |               192 B |
|                                       SelectConstructorsForInjection_InjectNonPublicIsTrue |   184.4 ns |  0.6296 ns |  0.5581 ns |      0.0188 |           - |           - |                80 B |
|                                      SelectConstructorsForInjection_InjectNonPublicIsFalse |   191.6 ns |  0.8963 ns |  0.7945 ns |      0.0284 |           - |           - |               120 B |
|                                            SelectMethodsForInjection_InjectNonPublicIsTrue | 5,594.1 ns | 59.6437 ns | 49.8052 ns |      0.6409 |           - |           - |              2696 B |
|                                           SelectMethodsForInjection_InjectNonPublicIsFalse | 4,068.7 ns | 22.9964 ns | 20.3857 ns |      0.4730 |           - |           - |              2008 B |
|   SelectPropertiesForInjection_InjectNonPublicIsTrueAndInjectParentPrivatePropertiesIsTrue | 3,794.6 ns | 14.2517 ns | 12.6338 ns |      0.4272 |           - |           - |              1800 B |
|  SelectPropertiesForInjection_InjectNonPublicIsTrueAndInjectParentPrivatePropertiesIsFalse | 2,293.6 ns | 11.0261 ns | 10.3138 ns |      0.2213 |           - |           - |               936 B |
|  SelectPropertiesForInjection_InjectNonPublicIsFalseAndInjectParentPrivatePropertiesIsTrue | 1,936.1 ns | 14.6617 ns | 13.7146 ns |      0.2594 |           - |           - |              1096 B |
| SelectPropertiesForInjection_InjectNonPublicIsFalseAndInjectParentPrivatePropertiesIsFalse | 1,359.9 ns |  8.5697 ns |  7.1561 ns |      0.1583 |           - |           - |               664 B |

**After:**

|                                                                                     Method |       Mean |      Error |     StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|------------------------------------------------------------------------------------------- |-----------:|-----------:|-----------:|------------:|------------:|------------:|--------------------:|
|                                                                                Constructor |   808.4 ns | 13.5499 ns | 12.0116 ns |      0.0362 |      0.0134 |      0.0029 |               152 B |
|                                       SelectConstructorsForInjection_InjectNonPublicIsTrue |   158.5 ns |  0.4753 ns |  0.4446 ns |      0.0112 |           - |           - |                48 B |
|                                      SelectConstructorsForInjection_InjectNonPublicIsFalse |   170.7 ns |  0.6720 ns |  0.5957 ns |      0.0207 |           - |           - |                88 B |
|                                            SelectMethodsForInjection_InjectNonPublicIsTrue | 4,929.5 ns | 57.3864 ns | 53.6793 ns |      0.2441 |           - |           - |              1032 B |
|                                           SelectMethodsForInjection_InjectNonPublicIsFalse | 3,691.8 ns | 62.1357 ns | 58.1218 ns |      0.2022 |           - |           - |               856 B |
|   SelectPropertiesForInjection_InjectNonPublicIsTrueAndInjectParentPrivatePropertiesIsTrue | 3,371.3 ns | 50.1827 ns | 46.9409 ns |      0.2670 |           - |           - |              1120 B |
|  SelectPropertiesForInjection_InjectNonPublicIsTrueAndInjectParentPrivatePropertiesIsFalse | 1,894.0 ns | 23.0300 ns | 20.4155 ns |      0.1373 |           - |           - |               576 B |
|  SelectPropertiesForInjection_InjectNonPublicIsFalseAndInjectParentPrivatePropertiesIsTrue | 1,627.6 ns | 13.5560 ns | 12.6803 ns |      0.1812 |           - |           - |               760 B |
| SelectPropertiesForInjection_InjectNonPublicIsFalseAndInjectParentPrivatePropertiesIsFalse | 1,109.5 ns | 14.8666 ns | 13.9062 ns |      0.1030 |           - |           - |               432 B |

### CODE REVIEW

**Comment by drieseng** [comment]
I'll look into the regression later today.

**Comment by drieseng** [comment]
@scott-xu This one's now ready to go :p

**Comment by scott-xu** [comment]
Is it benefited from **static** method?

**Comment by drieseng** [comment]
It's a combination of factors:
* Less argument checks
* Reduction in IL code size
* Elimination of captures
* Less virtual method invocations

We can reduce allocations (and perhaps improve performance) even more by eliminating more usage of Linq, but let's take it one step at a time.

**Comment by drieseng** [comment]
… and static methods are indeed cheaper than instance methods.

**Comment by drieseng** [comment]
@scott-xu Can we get this in?

**Comment by scott-xu** [comment]
This looks interesting: https://nessos.github.io/LinqOptimizer/

**Pull request merged**
