### PR TITLE
Expose internals of Ninject to Ninject.Test

### PR DESCRIPTION
**Pull request by drieseng**
Expose internals of **Ninject** to **Ninject.Test** to allows us to test internals.
Strongname **Ninject.Test**, and only optimize code in **Release** configuration (to allow us to debug tests).

### CODE REVIEW

**Comment by scott-xu** [comment]
I have a problem here. If optimize set to false, GC related unit tests will fail; if optimize set to true, we loose the ability to debug from visual studio. It’s not a issue about this PR. Just wondering if you have any idea about this scenario.

**Comment by drieseng** [comment]
As of this PR it's set to true for release builds, and false for debug builds.

So why not just use the release build config for the tests?

**Comment by drieseng** [comment]
Doesn't the fact that the unit tests all passed for this PR, means it's already OK?

**Comment by drieseng** [comment]
@scott-xu Do you need anything changed before we can get this in?

**Comment by drieseng** [comment]
Hey Scott, 

Do you think you'll have time soon to review the PRs I submitted? 
Can we come up with another solution that will not block any work I'm trying to do? 

Regards, 
Gert

**Pull request merged**
