### PR TITLE
Allow debugging of Ninject.Test project.

### LINKED ISSUE #302: Allow debugging of Ninject.Test project
Reintroduce support for debugging **Ninject.Test** project.
Was introduced in PR #277, but was reverted in ad2dd9b4fabcb6b1439de6c3804a7a143433478d before the PR was merged.

### PR DESCRIPTION
**Pull request by drieseng**
Reintroduce support for debugging **Ninject.Test** project.
Fixes #302.

### CODE REVIEW

**Comment by scott-xu** [comment]
Do we need to Define Constants explicitly?

**Comment by scott-xu** [comment]
Could you please try tick "Suppress JIT optimization on module load (managed only)" at Options->Debugging->General? If it works, we can 

1. make all UT pass even using debug configuration
2. debug Ninject.Test (hit break point, inspect variables, etc.)

**Comment by drieseng** [comment]
@scott-xu Apparently, we do not need to explicitly specify the **DEBUG** or **TRACE** symbols. VS build settings is badly broken as it shows the "Define DEBUG constant" as unchecked for the **Debug** config, but still sets it.

Changing the VS config indeed allows one to debug with optimizations turned on.
Another option is to make our tests pass with optimizations turned off.
That way, there's no need to update VS config.

I'm ok with whatever you prefer.

**Comment by scott-xu** [comment]
It would be best if we can make the tests pass with optimization turned off. However, GC does not behave the same between optimization on/off when tests are running under .NET Core.

**Comment by drieseng** [comment]
No, because locals are - for example - not collected immediately.
You can work around this by moving them into a separate method.
I'll have a look.

**Comment by drieseng** [comment]
Fixed by #338.

**Pull request closed without merging**
