### PR TITLE
Improve performance and allocations for extension methods

### PR DESCRIPTION
**Pull request by drieseng**
* Improves performance and reduces allocations for `ExtensionsForMemberInfo.GetPropertyFromDeclaredType(this MemberInfo memberInfo, PropertyInfo propertyDefinition, BindingFlags flags)`.
* Introduce member specific overloads of `ExtensionsForMemberInfo.HasAttribute(…)` to avoid type check when the concrete type is known.
* Add unit tests for `ExtensionsForMemberInfo.IsPrivate(this PropertyInfo propertyInfo)`, `ExtensionsForMemberInfo.HasAttribute(…)` overloads, and `ExtensionsForMemberInfo.GetPropertyFromDeclaredType(this MemberInfo memberInfo, PropertyInfo propertyDefinition, BindingFlags flags)`.
* Use "feature" symbols in **Directory.Build.props** to define capabilities of supported target frameworks.  Updated existing code to use new symbols.

**Before:**

|                                Method |     Mean |     Error |     StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------------------------------- |---------:|----------:|-----------:|------------:|------------:|------------:|--------------------:|
|   GetPropertyFromDeclaredType_Indexer | 416.2 ns | 8.1299 ns | 16.7897 ns |      0.0644 |           - |           - |               272 B |
| GetPropertyFromDeclaredType_NoIndexer | 164.3 ns | 0.6805 ns |  0.5682 ns |           - |           - |           - |                   - |

**After:**

|                                Method |      Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
-------------------------------------- |----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
   GetPropertyFromDeclaredType_Indexer | 261.95 ns | 3.4907 ns | 3.2652 ns |      0.0529 |           - |           - |               224 B |
 GetPropertyFromDeclaredType_NoIndexer |  88.96 ns | 0.7997 ns | 0.6678 ns |           - |           - |           - |                   - |

### CODE REVIEW

**Comment by scott-xu** [comment]
AssemblyScanning is a feature which depends on AppDomain Isolation, and may potentially depends on AssemblyLoadContext in the future. The feature can be turned on/off by NinjectSettings. So I’d suggest keep this symbol at this time.

**Comment by drieseng** [comment]
I'll update this PR accordingly.

**Comment by drieseng** [comment]
I changed my PR to use negative symbols again.

Can we consider changing **Ninject.Infrastructure.Array** back to **Ninject.Infrastructure.Arrays** again. I really don't think it's a good idea to "hide" **System.Array**.

**Comment by scott-xu** [comment]
Okay, I realized that alias Array hides the System.Array.
My original intention is to keep code as consistent as possible. With “Array” alias, the `Empty<T>` method has a consist way to consume. 
I’m just a little worried about the Array_Empty symbol because it brings more variants. 
Let’s move on for .NET Framework 4.6. 
Starting with Ninject 4.0, we only support .NET 4.6+ and .NET STANDARD 2.0+

**Comment by drieseng** [comment]
I understand, but I was more worried about consistent usage of symbols.
In case of Array.Empty<T>() we could indeed apply a static using.
But I doubt we ever run into such a situation again, and as such I preferred to apply the same technique we use for other framework-specific code.

I'm ok with moving to .NET Framework 4.6, and postponing this discussion until we need such a mechanism again.

I'll update this PR - and other PRs where I introduce the Arrays class - later today.
Is this the only thing blocking my other PRs?
If not, let me know what you want me to change.

**Comment by drieseng** [comment]
@scott-xu Can we get this in?

**Comment by scott-xu** [comment]
Sorry I should discuss first. After some thinking, I agree that the build-in symbols are not self-explained.
Let me rollback the change.

**Comment by drieseng** [comment]
No problem. You surely don't always have to agree with me.

**Pull request merged**
